"use client";

import React, { useEffect, useState, use } from "react";
import Image from "next/image";
import Link from "next/link";
import { 
  MapPin, Phone, MessageCircle, ArrowLeft, CheckCircle, 
  Loader2, Video, Map as MapIcon, Info, Star, User, Send
} from "lucide-react";

import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { StarRating } from "@/components/star-rating";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/contexts/AuthContext";

const APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbx1tMDo2KIq7mBLTWS1f8chuxPrqHx_IxgxrfFQ0Xo-tNKozHPTPU5znhnI3PY-4WSj/exec";

// Google Drive Link එක Direct Image එකක් බවට පත් කරන Function එක
const getDirectDriveLink = (url: string) => {
  if (!url || !url.includes("drive.google.com")) return url;
  const match = url.match(/\/d\/(.+?)\/(view|edit|usp|sharing)/);
  if (match && match[1]) {
    // FIXED: Corrected string interpolation syntax
    return `https://lh3.googleusercontent.com/u/0/d/${match[1]}`;
  }
  return url;
};


const getYoutubeEmbedUrl = (url: string): string | null => {
  if (!url) return null;
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
  const match = url.match(regExp);
  return (match && match[2].length === 11) 
    ? `https://www.youtube.com/embed/${match[2]}` 
    : null;
};

export default function ShopDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { user, isAuthenticated } = useAuth();
  const [shop, setShop] = useState<any>(null);
  const [reviews, setReviews] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Review Form States
  const [reviewName, setReviewName] = useState("");
  const [reviewRating, setReviewRating] = useState(5);
  const [hoverRating, setHoverRating] = useState(0);
  const [reviewComment, setReviewComment] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    if (user) {
      setReviewName(`${user.firstName} ${user.lastName}`.trim());
    }
  }, [user]);

  useEffect(() => {
    async function fetchData() {
      try {
        setLoading(true);
        const shopRes = await fetch(`${APPS_SCRIPT_URL}?action=getShops`);
        const allShops = await shopRes.json();
        const foundShop = allShops.find((s: any) => s.registration_no?.toString() === id || s.reg_no?.toString() === id);

        if (foundShop) {
          setShop({
            ...foundShop,
            displayImage: getDirectDriveLink(foundShop.image_url || foundShop.image) || "/placeholder.svg",
            ratingValue: foundShop.rating ? parseFloat(foundShop.rating) : 0,
            
            // --- FIXED REVIEW COUNT LOGIC ---
            // This checks multiple possible keys generated by your Apps Script
            reviewCount: parseInt(foundShop.review_count || foundShop.reviewcount || foundShop.reviews || 0),
            
            categoryList: foundShop.categories ? String(foundShop.categories).split(", ") : [],
            serviceList: foundShop.services ? String(foundShop.services).split(", ") : [],
            youtubeEmbed: getYoutubeEmbedUrl(foundShop.youtube_link),
            externalMapUrl: foundShop.map_url || foundShop.google_maps_url || foundShop.map_link
          });

          const revRes = await fetch(`${APPS_SCRIPT_URL}?action=getReviews&shopId=${id}`);
          const revData = await revRes.json();
          setReviews(revData);
        }
      } catch (error) {
        console.error("Error fetching data:", error);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, [id]);

  const handleReviewSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      await fetch(APPS_SCRIPT_URL, {
        method: "POST",
        mode: "no-cors",
        body: JSON.stringify({
          action: "addReview",
          shopId: id,
          name: reviewName,
          rating: reviewRating,
          comment: reviewComment
        })
      });
      alert("Review submitted successfully!");
      setReviewComment("");
      setReviewRating(5);
    } catch (err) {
      alert("Failed to submit review.");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (loading) return <div className="min-h-screen flex items-center justify-center"><Loader2 className="animate-spin text-primary w-10 h-10" /></div>;
  if (!shop) return <div className="min-h-screen flex flex-col items-center justify-center space-y-4 font-bold">Shop Not Found</div>;

  return (
    <div className="min-h-screen flex flex-col bg-slate-50 dark:bg-slate-950">
      <Header />
      <main className="flex-1 pb-20">
        <div className="max-w-7xl mx-auto px-4 py-6">
          <Link href="/shops" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"><ArrowLeft className="w-4 h-4" /> Back to Search</Link>
        </div>

        <section className="px-4 max-w-7xl mx-auto">
          {/* Shop UI Section */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 mb-12">
            <div className="relative aspect-square rounded-3xl overflow-hidden shadow-2xl bg-white border border-slate-200 dark:border-slate-800">
              <Image src={shop.displayImage} alt={shop.shop_name} fill className="object-cover" unoptimized priority />
            </div>
            <div className="flex flex-col justify-center">
              <div className="mb-2">
                <span className="text-primary text-sm font-bold uppercase tracking-wider">Verified Business</span>
                <h1 className="text-4xl md:text-5xl font-extrabold mt-1 tracking-tight text-slate-900 dark:text-white">{shop.shop_name}</h1>
                <p className="text-lg text-muted-foreground mt-2 font-medium italic">Owned by {shop.owner_name || "Valued Partner"}</p>
              </div>
              <div className="flex items-center gap-4 mb-8 py-2">
                <StarRating rating={shop.ratingValue} />
                <div className="flex flex-col border-l pl-4 border-slate-300">
                  <span className="font-bold text-xl leading-none">{shop.ratingValue > 0 ? shop.ratingValue : "New"}</span>
                  <span className="text-xs text-muted-foreground uppercase font-semibold">{shop.reviewCount} Reviews</span>
                </div>
              </div>
              <div className="space-y-5 mb-10">
                <div className="flex items-start gap-4"><div className="p-2 bg-primary/10 rounded-lg"><MapPin className="text-primary" size={20} /></div><p className="text-lg leading-snug">{shop.address}</p></div>
                <div className="flex items-center gap-4"><div className="p-2 bg-primary/10 rounded-lg"><Phone className="text-primary" size={20} /></div><p className="text-lg font-semibold">{shop.phone_number || shop.phone}</p></div>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
                <Button asChild size="lg" className="bg-[#25D366] hover:bg-[#128C7E] text-white shadow-lg"><a href={`https://wa.me/${shop.whatsapp_number || shop.phone}`} target="_blank" rel="noopener noreferrer"><MessageCircle className="mr-2 h-5 w-5" /> WhatsApp</a></Button>
                <Button variant="outline" size="lg" asChild className="shadow-sm border-2"><a href={`tel:${shop.phone_number || shop.phone}`}><Phone className="mr-2 h-5 w-5" /> Call Shop</a></Button>
              </div>
              <Button variant="secondary" size="lg" asChild className="w-full bg-blue-600 text-white hover:bg-blue-700 transition-all shadow-md"><a href={shop.externalMapUrl} target="_blank" rel="noopener noreferrer"><MapIcon className="mr-2 h-5 w-5" /> Get Directions</a></Button>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
            <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl border shadow-sm h-fit">
              <h3 className="text-2xl font-bold mb-6 flex items-center gap-3"><Info className="text-primary" /> Services Offered</h3>
              <div className="flex flex-wrap gap-3">
                {shop.serviceList.map((service: string, i: number) => (
                  <div key={i} className="flex items-center gap-2 px-5 py-2.5 bg-slate-50 dark:bg-slate-800 border rounded-xl text-sm font-medium"><CheckCircle size={16} className="text-green-500" /> {service}</div>
                ))}
              </div>
            </div>

            {shop.youtubeEmbed && (
              <div className="space-y-4">
                <h3 className="text-2xl font-bold flex items-center gap-3"><Video className="text-red-600" /> Video Showcase</h3>
                <div className="relative pt-[56.25%] rounded-3xl overflow-hidden shadow-2xl bg-black border border-slate-200">
                  <iframe className="absolute top-0 left-0 w-full h-full" src={shop.youtubeEmbed} title="YouTube video player" allowFullScreen></iframe>
                </div>
              </div>
            )}
          </div>

          <hr className="my-16 border-slate-200 dark:border-slate-800" />

          {/* PROFESSIONAL REVIEWS SECTION */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
            <div className="lg:col-span-1">
              <h3 className="text-2xl font-bold mb-4">Write a Review</h3>
              <form onSubmit={handleReviewSubmit} className="space-y-6 bg-white dark:bg-slate-900 p-6 rounded-2xl border shadow-sm">
                <div className="space-y-2">
                  <label className="text-sm font-semibold text-slate-700 dark:text-slate-300">Your Identity</label>
                  <Input 
                    placeholder={isAuthenticated ? "Your Name" : "Enter your name"} 
                    value={reviewName} 
                    onChange={(e) => setReviewName(e.target.value)} 
                    className="bg-slate-50 dark:bg-slate-800 border-none"
                    readOnly={isAuthenticated} 
                    required 
                  />
                  {isAuthenticated && (
                    <p className="text-xs text-muted-foreground">Logged in as {user?.email}</p>
                  )}
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-semibold text-slate-700 dark:text-slate-300">Rating</label>
                  <div className="flex gap-1">
                    {[1, 2, 3, 4, 5].map((star) => (
                      <button
                        key={star}
                        type="button"
                        onClick={() => setReviewRating(star)}
                        onMouseEnter={() => setHoverRating(star)}
                        onMouseLeave={() => setHoverRating(0)}
                        className="transition-transform hover:scale-110 focus:outline-none"
                      >
                        <Star 
                          size={32} 
                          className={`${
                            star <= (hoverRating || reviewRating) 
                              ? "text-yellow-400 fill-yellow-400" 
                              : "text-slate-300 dark:text-slate-700"
                          } transition-colors`}
                        />
                      </button>
                    ))}
                  </div>
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-semibold text-slate-700 dark:text-slate-300">Comment</label>
                  <Textarea 
                    placeholder="Tell others about your experience..." 
                    value={reviewComment} 
                    onChange={(e) => setReviewComment(e.target.value)} 
                    className="min-h-[120px] bg-slate-50 dark:bg-slate-800 border-none"
                    required 
                  />
                </div>

                <Button type="submit" className="w-full h-12 text-lg font-bold shadow-md" disabled={isSubmitting}>
                  {isSubmitting ? <Loader2 className="animate-spin" /> : <><Send className="mr-2 w-5 h-5" /> Post Review</>}
                </Button>
              </form>
            </div>

            <div className="lg:col-span-2">
              <h3 className="text-2xl font-bold mb-6 flex items-center gap-2">
                Feedback <span className="bg-primary/10 text-primary text-sm px-3 py-1 rounded-full">{reviews.length}</span>
              </h3>
              <div className="grid gap-4">
                {reviews.length > 0 ? (
                  reviews.map((rev, idx) => (
                    <div key={idx} className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-100 dark:border-slate-800 shadow-sm transition-hover hover:border-primary/20">
                      <div className="flex justify-between items-start mb-4">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center font-bold text-primary">
                            {rev.name?.charAt(0).toUpperCase() || <User size={20}/>}
                          </div>
                          <div>
                            <span className="font-bold block text-slate-900 dark:text-white">{rev.name}</span>
                            <span className="text-[11px] text-muted-foreground uppercase font-medium">
                              {new Date(rev.timestamp).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' })}
                            </span>
                          </div>
                        </div>
                        <div className="flex text-yellow-400">
                          {Array.from({ length: 5 }).map((_, i) => (
                            <Star key={i} size={14} fill={i < rev.rating ? "currentColor" : "none"} className={i >= rev.rating ? "text-slate-200" : ""} />
                          ))}
                        </div>
                      </div>
                      <p className="text-slate-600 dark:text-slate-400 leading-relaxed italic">"{rev.comment}"</p>
                    </div>
                  ))
                ) : (
                  <div className="text-center py-16 bg-white dark:bg-slate-900 rounded-3xl border-2 border-dashed border-slate-200 dark:border-slate-800">
                    <User className="mx-auto h-12 w-12 text-slate-300 mb-4" />
                    <p className="text-slate-500 font-medium">No one has reviewed this shop yet.</p>
                    <p className="text-sm text-slate-400">Be the first to share your thoughts!</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}