import type { Shop, Review, User } from './types';

export const shops: Shop[] = [
  {
    id: '1',
    reg_no: 'DMP-2024-001',
    shop_name: 'Dompe Super Center',
    shop_owner_name: 'Kamal Perera',
    phone_number: '+94 77 123 4567',
    whatsapp_number: '+94771234567',
    address: '125, Main Street, Dompe',
    services: ['Groceries', 'Fresh Vegetables', 'Household Items', 'Delivery Service'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    youtube_link: 'https://youtube.com',
    image: '/shops/grocery-shop.jpg',
    categories: ['grocery'],
    rating: 4.8,
    review_count: 156,
    created_at: '2024-01-15',
  },
  {
    id: '2',
    reg_no: 'DMP-2024-002',
    shop_name: 'Tech Zone Electronics',
    shop_owner_name: 'Nuwan Silva',
    phone_number: '+94 71 234 5678',
    whatsapp_number: '+94712345678',
    address: '45, Station Road, Dompe',
    services: ['Mobile Phones', 'Laptop Repairs', 'Accessories', 'TV Sales'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    image: '/shops/electronics-shop.jpg',
    categories: ['electronics'],
    rating: 4.5,
    review_count: 89,
    created_at: '2024-02-20',
  },
  {
    id: '3',
    reg_no: 'DMP-2024-003',
    shop_name: 'Fashion Hub',
    shop_owner_name: 'Malini Fernando',
    phone_number: '+94 76 345 6789',
    whatsapp_number: '+94763456789',
    address: '78, Temple Road, Dompe',
    services: ['Men\'s Wear', 'Women\'s Wear', 'Kids Clothing', 'Alterations'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    image: '/shops/clothing-shop.jpg',
    categories: ['clothing'],
    rating: 4.6,
    review_count: 124,
    created_at: '2024-01-05',
  },
  {
    id: '4',
    reg_no: 'DMP-2024-004',
    shop_name: 'Dompe Pharmacy',
    shop_owner_name: 'Dr. Saman Jayawardena',
    phone_number: '+94 77 456 7890',
    whatsapp_number: '+94774567890',
    address: '12, Hospital Road, Dompe',
    services: ['Prescription Medicines', 'OTC Drugs', 'Medical Equipment', 'Health Consultation'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    image: '/shops/pharmacy-shop.jpg',
    categories: ['pharmacy'],
    rating: 4.9,
    review_count: 203,
    created_at: '2023-12-10',
  },
  {
    id: '5',
    reg_no: 'DMP-2024-005',
    shop_name: 'Siri Bojun Restaurant',
    shop_owner_name: 'Chaminda Rathnayake',
    phone_number: '+94 71 567 8901',
    whatsapp_number: '+94715678901',
    address: '56, Bus Stand Road, Dompe',
    services: ['Rice & Curry', 'Kottu', 'Short Eats', 'Catering'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    youtube_link: 'https://youtube.com',
    image: '/shops/restaurant-shop.jpg',
    categories: ['restaurant'],
    rating: 4.7,
    review_count: 312,
    created_at: '2024-03-01',
  },
  {
    id: '6',
    reg_no: 'DMP-2024-006',
    shop_name: 'Builders Hardware',
    shop_owner_name: 'Rohan Wickramasinghe',
    phone_number: '+94 76 678 9012',
    whatsapp_number: '+94766789012',
    address: '89, Colombo Road, Dompe',
    services: ['Building Materials', 'Paints', 'Plumbing', 'Electrical Items'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    image: '/shops/hardware-shop.jpg',
    categories: ['hardware'],
    rating: 4.4,
    review_count: 67,
    created_at: '2024-02-15',
  },
  {
    id: '7',
    reg_no: 'DMP-2024-007',
    shop_name: 'Golden Bakery',
    shop_owner_name: 'Priyantha Gunawardena',
    phone_number: '+94 77 789 0123',
    whatsapp_number: '+94777890123',
    address: '23, School Lane, Dompe',
    services: ['Fresh Bread', 'Cakes', 'Pastries', 'Wedding Cakes'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    image: '/shops/bakery-shop.jpg',
    categories: ['bakery'],
    rating: 4.8,
    review_count: 198,
    created_at: '2024-01-20',
  },
  {
    id: '8',
    reg_no: 'DMP-2024-008',
    shop_name: 'Style Studio Salon',
    shop_owner_name: 'Nirmala Dissanayake',
    phone_number: '+94 71 890 1234',
    whatsapp_number: '+94718901234',
    address: '34, Market Street, Dompe',
    services: ['Haircuts', 'Hair Coloring', 'Bridal Makeup', 'Facial Treatments'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    image: '/shops/salon-shop.jpg',
    categories: ['salon'],
    rating: 4.6,
    review_count: 145,
    created_at: '2024-02-28',
  },
  {
    id: '9',
    reg_no: 'DMP-2024-009',
    shop_name: 'Auto Care Service',
    shop_owner_name: 'Sanjeewa Bandara',
    phone_number: '+94 76 901 2345',
    whatsapp_number: '+94769012345',
    address: '67, Gampaha Road, Dompe',
    services: ['Vehicle Service', 'Oil Change', 'Tyre Service', 'Battery Replacement'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    image: '/shops/automotive-shop.jpg',
    categories: ['automotive'],
    rating: 4.5,
    review_count: 92,
    created_at: '2024-03-10',
  },
  {
    id: '10',
    reg_no: 'DMP-2024-010',
    shop_name: 'Gem Palace Jewelry',
    shop_owner_name: 'Lalith Senanayake',
    phone_number: '+94 77 012 3456',
    whatsapp_number: '+94770123456',
    address: '101, Main Street, Dompe',
    services: ['Gold Jewelry', 'Gem Stones', 'Wedding Rings', 'Repairs'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    image: '/shops/jewelry-shop.jpg',
    categories: ['jewelry'],
    rating: 4.9,
    review_count: 78,
    created_at: '2024-01-30',
  },
  {
    id: '11',
    reg_no: 'DMP-2024-011',
    shop_name: 'Fresh Mart Grocery',
    shop_owner_name: 'Anura Herath',
    phone_number: '+94 71 123 4567',
    whatsapp_number: '+94711234567',
    address: '45, Temple Road, Dompe',
    services: ['Fresh Produce', 'Dairy Products', 'Snacks', 'Home Delivery'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    image: '/shops/grocery-shop.jpg',
    categories: ['grocery'],
    rating: 4.3,
    review_count: 112,
    created_at: '2024-02-05',
  },
  {
    id: '12',
    reg_no: 'DMP-2024-012',
    shop_name: 'Quick Print Services',
    shop_owner_name: 'Dilshan Mendis',
    phone_number: '+94 76 234 5678',
    whatsapp_number: '+94762345678',
    address: '78, Station Road, Dompe',
    services: ['Printing', 'Photocopying', 'Laminating', 'ID Cards'],
    google_maps_url: 'https://maps.google.com/?q=Dompe,Sri+Lanka',
    image: '/shops/services-shop.jpg',
    categories: ['services'],
    rating: 4.4,
    review_count: 56,
    created_at: '2024-03-15',
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    shop_id: '1',
    user_id: 'user1',
    user_name: 'Amali W.',
    rating: 5,
    comment: 'Excellent selection of products and very friendly staff. Always fresh vegetables!',
    created_at: '2024-03-15',
  },
  {
    id: '2',
    shop_id: '1',
    user_id: 'user2',
    user_name: 'Ranjan K.',
    rating: 4,
    comment: 'Good prices and convenient location. Could improve parking facilities.',
    created_at: '2024-03-10',
  },
  {
    id: '3',
    shop_id: '2',
    user_id: 'user3',
    user_name: 'Shanika P.',
    rating: 5,
    comment: 'Fixed my phone quickly and at a reasonable price. Highly recommend!',
    created_at: '2024-03-12',
  },
  {
    id: '4',
    shop_id: '5',
    user_id: 'user4',
    user_name: 'Kumara S.',
    rating: 5,
    comment: 'Best kottu in Dompe! The taste is amazing and portions are generous.',
    created_at: '2024-03-18',
  },
  {
    id: '5',
    shop_id: '4',
    user_id: 'user5',
    user_name: 'Dilini M.',
    rating: 5,
    comment: 'Very professional service. Dr. Saman always gives helpful advice.',
    created_at: '2024-03-08',
  },
];

export const currentUser: User | null = null;

export function getShopById(id: string): Shop | undefined {
  return shops.find(shop => shop.id === id);
}

export function getReviewsByShopId(shopId: string): Review[] {
  return reviews.filter(review => review.shop_id === shopId);
}

export function getShopsByCategory(category: string): Shop[] {
  if (category === 'all') return shops;
  return shops.filter(shop => shop.categories.includes(category));
}

export function searchShops(query: string): Shop[] {
  const lowercaseQuery = query.toLowerCase();
  return shops.filter(shop => 
    shop.shop_name.toLowerCase().includes(lowercaseQuery) ||
    shop.services.some(service => service.toLowerCase().includes(lowercaseQuery)) ||
    shop.address.toLowerCase().includes(lowercaseQuery) ||
    shop.categories.some(cat => cat.toLowerCase().includes(lowercaseQuery))
  );
}
